<map id="pip._vendor.urllib3.exceptions.TimeoutError" name="pip._vendor.urllib3.exceptions.TimeoutError">
<area shape="rect" id="node4" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ConnectTimeoutError.html" title="pip._vendor.urllib3.exceptions.\lConnectTimeoutError" alt="" coords="627,5,825,47"/>
<area shape="rect" id="node6" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ReadTimeoutError.html" title="pip._vendor.urllib3.exceptions.\lReadTimeoutError" alt="" coords="627,71,825,112"/>
<area shape="rect" id="node2" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1HTTPError.html" title="pip._vendor.urllib3.exceptions.\lHTTPError" alt="" coords="133,39,332,80"/>
<area shape="rect" id="node5" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1NewConnectionError.html" title="pip._vendor.urllib3.exceptions.\lNewConnectionError" alt="" coords="873,5,1072,47"/>
</map>
