\hypertarget{classpip_1_1__internal_1_1exceptions_1_1BadCommand}{}\section{pip.\+\_\+internal.\+exceptions.\+Bad\+Command Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1BadCommand}\index{pip.\+\_\+internal.\+exceptions.\+Bad\+Command@{pip.\+\_\+internal.\+exceptions.\+Bad\+Command}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=202pt]{classpip_1_1__internal_1_1exceptions_1_1BadCommand__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Bad\+Command\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=202pt]{classpip_1_1__internal_1_1exceptions_1_1BadCommand__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Raised when virtualenv or a command is not found\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pip/\+\_\+internal/\hyperlink{pip_2__internal_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
