\hypertarget{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout}{}\section{pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout Class Reference}
\label{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout}\index{pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout@{pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout}}


Inheritance diagram for pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+vendor.\+requests.\+exceptions.\+Connect\+Timeout\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__vendor_1_1requests_1_1exceptions_1_1ConnectTimeout__coll__graph}
\end{center}
\end{figure}
\subsection*{Additional Inherited Members}


\subsection{Detailed Description}
\begin{DoxyVerb}The request timed out while trying to connect to the remote server.

Requests that produced this error are safe to retry.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pip/\+\_\+vendor/requests/\hyperlink{pip_2__vendor_2requests_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
