\hypertarget{classnetworkx_1_1exception_1_1NetworkXNoPath}{}\section{networkx.\+exception.\+Network\+X\+No\+Path Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXNoPath}\index{networkx.\+exception.\+Network\+X\+No\+Path@{networkx.\+exception.\+Network\+X\+No\+Path}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+No\+Path\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXNoPath__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+No\+Path\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXNoPath__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception for algorithms that should return a path when running
on graphs where such a path does not exist.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
