\hypertarget{classnetworkx_1_1exception_1_1NetworkXException}{}\section{networkx.\+exception.\+Network\+X\+Exception Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXException}\index{networkx.\+exception.\+Network\+X\+Exception@{networkx.\+exception.\+Network\+X\+Exception}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classnetworkx_1_1exception_1_1NetworkXException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXException__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Base class for exceptions in NetworkX.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
