\hypertarget{classpytz_1_1exceptions_1_1NonExistentTimeError}{}\section{pytz.\+exceptions.\+Non\+Existent\+Time\+Error Class Reference}
\label{classpytz_1_1exceptions_1_1NonExistentTimeError}\index{pytz.\+exceptions.\+Non\+Existent\+Time\+Error@{pytz.\+exceptions.\+Non\+Existent\+Time\+Error}}


Inheritance diagram for pytz.\+exceptions.\+Non\+Existent\+Time\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=223pt]{classpytz_1_1exceptions_1_1NonExistentTimeError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pytz.\+exceptions.\+Non\+Existent\+Time\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=223pt]{classpytz_1_1exceptions_1_1NonExistentTimeError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception raised when attempting to create a wallclock time that
cannot exist.

At the start of a DST transition period, the wallclock time jumps forward.
The instants jumped over never occur.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pytz/\hyperlink{pytz_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
