\hypertarget{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1UnrewindableBodyError}{}\section{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Unrewindable\+Body\+Error Class Reference}
\label{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1UnrewindableBodyError}\index{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Unrewindable\+Body\+Error@{pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Unrewindable\+Body\+Error}}


Inheritance diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Unrewindable\+Body\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=229pt]{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1UnrewindableBodyError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+vendor.\+urllib3.\+exceptions.\+Unrewindable\+Body\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=229pt]{classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1UnrewindableBodyError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}urllib3 encountered an error when trying to rewind a body\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pip/\+\_\+vendor/urllib3/\hyperlink{pip_2__vendor_2urllib3_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
