\hypertarget{classpytz_1_1exceptions_1_1Error}{}\section{pytz.\+exceptions.\+Error Class Reference}
\label{classpytz_1_1exceptions_1_1Error}\index{pytz.\+exceptions.\+Error@{pytz.\+exceptions.\+Error}}


Inheritance diagram for pytz.\+exceptions.\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpytz_1_1exceptions_1_1Error__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pytz.\+exceptions.\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=190pt]{classpytz_1_1exceptions_1_1Error__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Base class for all exceptions raised by the pytz library\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/pytz/\hyperlink{pytz_2exceptions_8py}{exceptions.\+py}\end{DoxyCompactItemize}
